### ISSUE TITLE
QA for the Python SDK

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis.py#1]

**Comment by iteachmachines** [comment]
I would love to work in it.

**Comment by yanivbh1** [comment]
@iteachmachines Let's go! :)
My recommendation would be to create a benchmark app and test it with different workloads/payloads

**Comment by iteachmachines** [comment]
Sure

**Comment by Adarsh-jaiss** [comment]
- hey @SvetaMemphis , is anyone is working on this issue? 
- if not then, can you please elaborate this issue because I am pretty confused

**Comment by Adarsh-jaiss** [comment]
- Hey @SvetaMemphis , after trying a lot on my pc, sadly I want to inform you that I can't work on this issue, because I don't have enough resources in my laptop (I.e i have a very old laptop right now, earlier I used to work on my brother's pc, but now I moved out from my city for higher education and currently I am using that old laptop! 

And it has some compatibility issues, so I can't work on this issue!  Right now :(

**Comment by yanivbh1** [comment]
All understood, @Adarsh-jaiss. Thanks.
