### ISSUE TITLE
lint project using Ruff

### ISSUE THREAD

**Issue by alon-david** [memphisdev/memphis.py#173]
Ruff is a rust based python linter that enforces beautiful code standard. Can I apply it to this package? 
https://github.com/astral-sh/ruff#ruff

**Comment by yanivbh1** [comment]
Hey @alon-david , thanks for the idea.
@rnowling-memphis any thoughts?

**Comment by rnowling-memphis** [comment]
Thanks for the suggestion @alon-david .  We recently started using Pylint (older but serves a similar function).  Our code base is pretty small so run-time isn't much of an issue, but the team is still adjusting to using Pylint effectively in our work.  I'm hesitant to do a bait and switch on them until they are at least comfortable using Pylint as a tool rather than seeing it as a hinderance.  :)  E.g., I'd like to get to a point where the code base is clean enough that we aren't disabling any of the Pylint checks.

**Comment by idanasulinmemphis** [comment]
Hi @alon-david, thank you for this one absolutely amazing but I had to say that I agree with @rnowling-memphis
